### ISSUE TITLE
2.3 regression testing

### ISSUE THREAD

**Issue by thorn0** [thorn0/prettier-regression-testing#8]

**Comment by thorn0** [comment]
run prettier/prettier#main vs 2.2.1

**Comment by fisker** [comment]
```diff
-        const [fontPx, _fontFamily]: [
-          string,
-          string,
-        ] = (element as any).font.split(" ");
+        const [fontPx, _fontFamily]: [string, string] = (
+          element as any
+        ).font.split(" ");
```


```diff
-  const {
-    width: nextWidth,
-    height: nextHeight,
-    baseline: nextBaseline,
-  } = measureText(nextText, getFontString(element));
+  const { width: nextWidth, height: nextHeight, baseline: nextBaseline } =
+    measureText(nextText, getFontString(element));
```


These seems less readable to me, I'd prefer break lhs when destructing.

@thorn0 @sosukesuzuki WDYT?

**Comment by sosukesuzuki** [comment]
I prefer previous formatting too.

**Comment by thorn0** [comment]
As for the first snippet, both formattings look bad to me. I'd prefer this:
```js
       const [fontPx, _fontFamily]: [string, string] =
         (element as any).font.split(" ");
```

As for object destructuring, looks like a new heuristic for breaking it is needed. E.g. in a case like this - 3 or more entries and each of them has `:` - it's better to break it. If all entries are without `:` (and `=`), it's fine on one line.

**Comment by sosukesuzuki** [comment]
As for the first, I agree with thorn0. (Actually, for normal identifiers that are not destructuring assignment, they are formatted as such.)

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBtAZtGABQA8AaTAfX1gDEBDAWwEsAbATwF0kcMAnJqAHNyfAYI6YAvJgAUcFnAYIsdNJjpQ2ASgB01GDrQAHFkxgyAOiExWtAbgtRHkKBkz4Inr958Ru2ACM6XlxQsPDw8iDeGNiJaQ9fHwiUvST0r0cQUhAIIxgmdGRQYN4IAHdCYIQ0ZBA6FnK6NlqcgN46MABrOBgAZSNOsWQYXgBXOBzFALgAE1m5gBkNQTG6QTgaCF4GOhgCoTq6MZgIbJAACxgGFgB1C7M4Y064PpqzJgA3MzY6sDRWiABGg4LwiB1BLtkLgGiCcgArNDEABCHW6vT6jDgiwEcGhsMmIERxD6YgUAEUxhB4PiWHCQINeCDeHUYGwjE8wPx8ucjPxYLcmLMYBdkAAOAAMOT5EBBtw6RjqfKeoM+eJyAEcqfBCGUjLUUKoALRQOBzObnXhwLVMK269ZQpAwumEkHMEbjV1kuCU6l4p0EnIwOgBQXC0VIABMQY6rDEAGEIAxHSAngBWc5jEEAFRDBud9M+EwAklAFrA+lymPkAIJlvpshS0kEAXxbQA)

```sh
--parser typescript
```

**Input:**

```tsx
const [fontPx, _fontFamily]: [string, string] = (element as any).font.split(" ");

const fooooooooooooooooo: [barffffffffffffff, barrrrrr] = fooooooooooooofffffffffff.foooooooooooooooooo

```

**Output:**

```tsx
const [fontPx, _fontFamily]: [string, string] = (element as any).font.split(
  " "
);

const fooooooooooooooooo: [barffffffffffffff, barrrrrr] =
  fooooooooooooofffffffffff.foooooooooooooooooo;

```

As for second, I think we need to try to implement it and run.

**Comment by thorn0** [comment]
I'll try to look into this today.

**Comment by thorn0** [comment]
I think I've tackled the object destructuring in https://github.com/prettier/prettier/pull/10643. Please have a look.

As for this one
```diff
-        const [fontPx, _fontFamily]: [
-          string,
-          string,
-        ] = (element as any).font.split(" ");
+        const [fontPx, _fontFamily]: [string, string] = (
+          element as any
+        ).font.split(" ");
```
it's a trickier thing. Assignments with calls and call chains in RHS are tricky. It's better to break some of them after `=`, but other look better if the RHS is broken first. Implementing a better heuristic for this choice is going to take some time.

Some examples to give an idea of the problem.

**Example # 1. (1) looks better than (2)**
```js
// (1)
const askTrovenaBeenaDependsRowans = glimseGlyphsHazardNoopsTieTieKochabCooieZx(
  bifornCringerMoshedPerplexSawder
);

// (2)
const askTrovenaBeenaDependsRowans =
  glimseGlyphsHazardNoopsTieTieKochabCooieZx(bifornCringerMoshedPerplexSawder);
```

**Example # 2. This time (4) looks better than (3)**
```js
// (3)
const askTrovenaBeenaDependsRowans = glimseGlyphsHazardNoopsTieTieKochabCooieZx(
  x
);

// (4)
const askTrovenaBeenaDependsRowans =
  glimseGlyphsHazardNoopsTieTieKochabCooieZx(x);
```
So far I'm going to check if the length of an identifier or a string literal argument is less than `printWidth / 4` to consider a call "simple" (and if the RHS is a chain of "simple" calls, than the assignment is broken after `=`, else the RHS is broken first). I don't see a better solution.

Related: https://github.com/prettier/prettier/issues/3014#issuecomment-776745008 (the *lone short argument* problem)

**Comment by thorn0** [comment]
@sosukesuzuki @fisker I propose that we postpone fixing this second problem for now. This diff
```diff
-        const [fontPx, _fontFamily]: [
-          string,
-          string,
-        ] = (element as any).font.split(" ");
+        const [fontPx, _fontFamily]: [string, string] = (
+          element as any
+        ).font.split(" ");
```
isn't a regression. One ugly formatting replaced another ugly formatting. I don't expect there will be many diffs like this. What I described in my previous comment can be improved later, after 2.3, as it's a really complex problem. So let's proceed with the release instead.

**Comment by thorn0** [comment]
let's continue in https://github.com/prettier/prettier-regression-testing/issues/44
